[YouTube]
apkmirror-arch = "arm64-v8a"
excluded-patches = "'Theme' 'Enable debugging'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
apkmirror-arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
