[YouTube]
apkmirror-arch = "arm64-v8a"
excluded-patches = "'Theme' 'Enable debugging'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
apkmirror-arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
