[YouTube]
arch = "arm64-v8a"
excluded-patches = "'Enable debugging'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
